language: java
sudo: required
dist: trusty
install: true

addons:
  sonarcloud:
    organization: "noraui"
  chrome: stable

jdk:
- oraclejdk8

before_script:
- chmod +x test/run.sh

script:
- test/run.sh

cache:
  directories:
    - $HOME/.m2/repository
